### PR TITLE
Add source to list all issues.

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
* helm-open-github.el: Do it.
Cache also candidates in hashtable, sources use in-buffer.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Just a first shotto fix #7, not fully verified, seems it is working on my helm repos.
Please review, I will modify in consequence.
Thanks.

**Comment by syohex** [comment]
Looks good.

**Comment by syohex** [comment]
Thanks for implementing nice features.
However it is better to improve `gh.el` APIs.

**Comment by thierryvolpiatto** [comment]
Syohei YOSHIDA <notifications@github.com> writes:

> Thanks for implementing nice features.

Thanks to you for this, it helps a lot finding issues.

> However it is better to improve gh.el APIs.

Agree, probably the defmethod should go to gh.el, maybe the author will
make a more generic method for use with different args for github API.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Pull request merged**
